### ISSUE TITLE
Conflict Between Exodus & AlgoSigner?

### ISSUE THREAD

**Issue by SilentRhetoric** [TxnLab/use-wallet#17] opened 2022-11-21 02:33 UTC
#### Issue description

Using Exodus and AlgoSigner wallets in the same Chrome browser causes a conflict

#### Steps to reproduce the issue

1. Chrome Version 107.0.5304.110 (Official Build) (arm64)
2. Both extensions for Exodus and AlgoSigner are installed and active
3.  Visit [https://gabrielkuettel.github.io/use-wallet-example/](https://gabrielkuettel.github.io/use-wallet-example/)
4. Connect to Exodus and see the account shown in the app
5. Connect to AlgoSigner and the Exodus account will appear under AlgoSigner instead of the account from AlgoSigner (this is most obvious if you use different accounts in Exodus/AlgoSigner

#### What's the expected result?

Connecting AlgoSigner should not be picking up the account from Exodus wallet; it should return the account that AlgoSigner has.

#### What's the actual result?

The Exodus account will appear under AlgoSigner instead of the account from AlgoSigner

#### Additional details / screenshot

If the Chrome extensions are disabled so that only one is active at a time, they will work fine on their own.

**Comment by stefdegroot** [comment] 2022-12-05 10:17
This issue is caused by Exodus and can unfortunately not be fixed from the developer's side. Exodus will, by default, override other wallet extensions and prioritize itself. The user/client can turn this off in their settings by disabling "Prioritize Exodus".

![image](https://user-images.githubusercontent.com/23223516/205611594-a67850ba-796e-454d-85ca-f522b353fb64.png)

**Comment by gabrielkuettel** [comment] 2022-12-07 23:35
Thank you @stefdegroot for chiming in with this. I did not have this setting enabled (I guess it's disabled by default?) so I was not able to reproduce this issue, but enabling this setting does in fact cause it. I would've been racking my brain trying to figure this one out! 

@SilentRhetoric can you confirm that disabling this setting solves the issue?

**Comment by SilentRhetoric** [comment] 2022-12-08 00:27
> @SilentRhetoric can you confirm that disabling this setting solves the issue?

Yes, disabling this "Prioritize Exodus" setting allowed me to connect with Exodus first and then AlgoSigner second without the account from Exodus being provided as the AlgoSigner account.  

Thank you very much @stefdegroot for sharing this information, which will no doubt save developers headaches trying to debug this in their code and probably also some multi-wallet users who may be very confused by this Exodus "prioritize" behavior.

**Comment by gabrielkuettel** [comment] 2022-12-08 18:44
Great. Closing this. Thanks again for your contributions here @SilentRhetoric @stefdegroot .

**Closed** 2022-12-08 18:44 UTC
