### ISSUE TITLE
Failed to connect to kibisis

### ISSUE THREAD

**Issue by AChaffangeon** [TxnLab/use-wallet#203] opened 2024-07-28 08:56 UTC
When trying the vue project, the connection to Kibisis failed. Firstly, the npm installation failed to import the dependency to @agoralabs-sh/algorand-provider. After installing it manually, here's what happens when you click on "Connect":
<img width="627" alt="Screenshot 2024-07-28 at 10 55 18" src="https://github.com/user-attachments/assets/dbe24184-ad74-41ad-bd93-dc9a98b62e47">

**Comment by drichar** [comment] 2024-07-29 03:20
The wallet dependencies need to be installed manually in your application, since they are optional and depend on which wallet(s) are included in your configuration.

Can you provide a link to your project's source code, or a minimal reproduction example? If not, can you share some details about your Vue app? This will help me recreate the error you're getting so I can isolate the issue.

**Comment by drichar** [comment] 2024-09-24 19:38
This is fixed in https://github.com/TxnLab/use-wallet/releases/tag/v3.4.0

**Closed by drichar** 2024-09-24 19:38 UTC
