### ISSUE TITLE
[Bug] Package is forcing installation of optional peer dependencies 

### ISSUE THREAD

**Issue by aorumbayev** [TxnLab/use-wallet#67] opened 2023-04-02 11:08 UTC
## Description

Upon installation of the package, if user wants to only use N out of M total supported providers (for example only pera, defly), use-wallet fails to load on the error below if other peer wallet providers aren't installed:

<img width="985" alt="Screenshot 2023-04-02 at 13 05 51" src="https://user-images.githubusercontent.com/7698600/229348960-257f98b3-a188-4ee9-a167-c510141d40fc.png">

## Steps to replicate

1. Clone https://github.com/subtopia-algo/subtopia-js-examples/tree/main/NextJS
2. Exclude myalgo wallet from package.json
3. do yarn install
4. do yarn dev and observe error

**Comment by drichar** [comment] 2023-04-03 19:52
I was able to reproduce this locally, in both the Next.js example and the Create React App example.

@randlabs/myalgo-connect is being dynamically imported in the `MyAlgoWalletClient` class's `init` method, and since you're not passing `PROVIDER_ID.MYALGO` to `initializeProviders`, Next.js shouldn't be trying to find it.

I'll see if wrapping the dynamic imports in a try/catch block prevents the build process from failing.

Next has their own `next/dynamic` library for handling dynamic imports, maybe that's because it doesn't correctly handle ES6 dynamic imports?

**Comment by drichar** [comment] 2023-04-03 20:08
Actually @aorumbayev I was able to resolve the issue in your Next.js example by running

```shell
$ rm -rf package-lock.json node_modules/
$ yarn install
$ yarn dev
```

You have both a package-lock.json file and yarn.lock file, so when I first ran `yarn install` I got the warning:

```shell
$ yarn
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

Same case with the Create React App example, but the error still occurs after reinstalling packages. I'll see if the try/catch around the dynamic imports resolves it.

**Comment by aorumbayev** [comment] 2023-04-04 07:03
Yeah this is the line that causes the error:
```
const MyAlgoConnect = clientStatic || (await import('@randlabs/myalgo-connect')).default;
```

If it won't work out with next/dynamic, pretty sure at least try/catch should work for now

**Comment by drichar** [comment] 2023-04-26 21:39
The optional dependencies had to be set as optional in `peerDependenciesMeta` in package.json. Upgrading to @txnlab/use-wallet to v1.3.0-alpha.0 in your example repo and following the reproduction steps, the app should build successfully.

Let me know if it works for you @aorumbayev

**Comment by drichar** [comment] 2023-04-28 18:08
Fixed in https://github.com/TxnLab/use-wallet/releases/tag/v1.3.0

**Closed by drichar** 2023-04-28 18:08 UTC
